print("Cálculo de média ponderada para três notas.\n|\nV")
nota1 = float(input("Insira a primeira nota:\n"))
peso1 = float(input("Insira o peso da primeira nota?\n"))
nota2 = float(input("Insira a segunda nota:\n"))
peso2 = float(input("Insira o peso da segunda nota?\n"))
nota3 = float(input("Insira a terceira nota\n"))
peso3 = float(input("Insira o peso da terceira nota?\n"))
media = (nota1 * peso1 + nota2 * peso2 + nota3 * peso3) / (peso1 + peso2 + peso3)
print("A média ponderada das notas foi: " + str(media))
